import QtQuick
import Halcyon.Ui
import Halcyon.Engine

// The default stage: video (§0.3, §P1.2).
//
// This is `ModeSpec.stage_qml`'s default. Local and M3U both use it unchanged —
// the same pipeline, the same surface, no per-mode video code. Web overrides it
// (§P3.3).
//
// Two pixel paths, chosen at runtime by what the ring actually holds:
//   planar (I420) -> ShaderEffect samples Y/U/V, BT.709 in a fragment shader
//   packed (RV32) -> the surface draws itself, no shader
Item {
    id: root

    readonly property alias surface: videoSurface

    // Null-guarded on purpose. During teardown Qt destroys the VideoSurface
    // child before the bindings that read it are torn down, so an unguarded
    // `videoSurface.hasVideo` prints "Cannot read property of null" on every
    // exit. The guard costs nothing and keeps the shutdown log honest.
    readonly property bool hasVideo: videoSurface ? videoSurface.hasVideo : false
    readonly property rect contentRect: videoSurface ? videoSurface.contentRect
                                                     : Qt.rect(0, 0, 0, 0)

    VideoSurface {
        id: videoSurface
        anchors.fill: parent
        fillMode: 1                      // PreserveAspectFit

        // RV32 fallback draws through the item itself; in planar mode the item
        // contributes nothing and the ShaderEffect below does the drawing.
        visible: !isPlanar
    }

    // Bind the surface to the player once, when both exist.
    //
    // `setSource` is typed `QObject*`. Handing it a Python module — which is
    // what `Player` was before main.py stopped shadowing its own engine
    // instance — raised "Passing incompatible arguments to C++ functions from
    // JavaScript is not allowed" and left the stage permanently black. The
    // typeof guard keeps this file loadable in isolation (qmlscene, tests)
    // where no Player context property is installed at all.
    Component.onCompleted: root.attachPlayer()

    function attachPlayer() {
        if (typeof Player === "undefined" || !Player) {
            console.warn("VideoStage: no Player context object — stage will stay blank");
            return;
        }
        videoSurface.setSource(Player);
    }

    // YUV -> RGB. Loaded only on the planar path, and only when a compiled
    // shader is actually present.
    //
    // This is a Loader rather than a bare ShaderEffect with `visible: false`
    // because an invisible ShaderEffect is still *constructed*: Qt tries to
    // deserialise the .qsb, fails, and prints the whole "Failed to find shader
    // / shader preparation failed" wall even when the RV32 path is the one
    // drawing the picture. Not instantiating it is the only way to not see it.
    Loader {
        id: shaderLoader
        active: videoSurface ? videoSurface.isPlanar : false
        x: root.contentRect.x
        y: root.contentRect.y
        width: root.contentRect.width
        height: root.contentRect.height
        sourceComponent: yuvComponent
    }

    Component {
        id: yuvComponent

        ShaderEffect {
            visible: root.hasVideo

            // Must match the sampler names in yuv420p.frag. They are texY/texU/texV
            // rather than y/u/v because `property variant y` shadows Item.y, which
            // QML rejects outright ("Property value set multiple times").
            property variant texY: videoSurface.planeY
            property variant texU: videoSurface.planeU
            property variant texV: videoSurface.planeV

            // Relative to this file, so it resolves both from a source checkout and
            // from qrc: in a packaged build. Generated by tools/build_shaders.py.
            fragmentShader: Qt.resolvedUrl("../shaders/yuv420p.frag.qsb")

            onStatusChanged: {
                if (status === ShaderEffect.Error) {
                    console.warn("YUV shader failed to load — run"
                                 + " `python tools/build_shaders.py`, or set"
                                 + " video.backend='rv32' in Settings to fall back:",
                                 log);
                }
            }
        }
    }

    // Double-click toggles fullscreen — the *same* action as the transport
    // button and the F key (§4.1). Not a second implementation.
    MouseArea {
        anchors.fill: parent
        acceptedButtons: Qt.LeftButton
        onDoubleClicked: Actions.toggleFullscreen()
        onClicked: Actions.playPause()
    }
}
